/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "cy_sysint.h"
#include "cy_tcpwm_counter.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Configuration for timer instance 0, Group 0, Counter 1 and used interrupt */
#define TCPWM_INTR_SOURCE  CY_TCPWM_INT_ON_TC

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* Peripheral interrupt configuration structure */
const cy_stc_sysint_t IRQ_CFG_PERIPHERAL =
{
    .intrSrc  = ((NvicMux5_IRQn << 16) | tcpwm_0_interrupts_1_IRQn),
    .intrPriority = 3UL
};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/**********************************************************************************************************************
 * Function Name: handle_Counter_Interrupt_0
 * Summary:
 *  This function implements the interrupt handler, which is called by a peripheral based software triggered interrupt.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
void handle_Counter_Interrupt_0(void)
{
     /* Clear TCPWM TC interrupt flag */
    Cy_TCPWM_ClearInterrupt(TCPWM_PWM_HW, TCPWM_PWM_NUM, TCPWM_INTR_SOURCE);
    /* Toggle the USER LED state */
    cyhal_gpio_toggle(CYBSP_USER_LED2);
}

/**********************************************************************************************************************
 * Function Name: init_Timer_Interrupt
 * Summary:
 *  This function sets up and initializes the TCPWM0 group 0 counter 1 timer and enables software to set the terminal
 *  count interrupt.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
static void init_Timer_Interrupt(void)
{
    /* Initialize TCPWM0_GRP0_COUNTER 1 as Counter */
    CY_ASSERT(Cy_TCPWM_Counter_Init(TCPWM_PWM_HW,TCPWM_PWM_NUM, &TCPWM_PWM_config) == CY_TCPWM_SUCCESS);
    /* Enable TCPWM0_GRP0_COUNTER 1 */
    Cy_TCPWM_Counter_Enable(TCPWM_PWM_HW, TCPWM_PWM_NUM);

    /* Enable desired interrupt for the counter */
    Cy_TCPWM_SetInterruptMask(TCPWM_PWM_HW, TCPWM_PWM_NUM, TCPWM_INTR_SOURCE);

    /*  Setting up the peripheral interrupt */
    CY_ASSERT(Cy_SysInt_Init(&IRQ_CFG_PERIPHERAL, handle_Counter_Interrupt_0) == CY_SYSINT_SUCCESS);
    /* Enable the peripheral interrupt mapped to NVICMux5 */
    NVIC_EnableIRQ(NvicMux5_IRQn);
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
int main(void)
{
    uint8_t uartReadValue;      /* Variable for storing character read from terminal */

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    CY_ASSERT(cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms()) == CY_RSLT_SUCCESS);
    cyhal_wdt_free(&wdt_obj);
#endif

    /* Initialize the device and board peripherals */
    CY_ASSERT(cybsp_init() == CY_RSLT_SUCCESS);

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    CY_ASSERT(cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX,
                                  CY_RETARGET_IO_BAUDRATE) == CY_RSLT_SUCCESS);

    /* Initialize the User LED 1 and 2 */
    CY_ASSERT(cyhal_gpio_init(CYBSP_USER_LED1, CYHAL_GPIO_DIR_OUTPUT,
                              CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF) == CY_RSLT_SUCCESS);
    CY_ASSERT(cyhal_gpio_init(CYBSP_USER_LED2, CYHAL_GPIO_DIR_OUTPUT,
                              CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF) == CY_RSLT_SUCCESS);

    /* Initialize TCPWM based software interrupts */
    init_Timer_Interrupt();

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "Software Interrupt using Peripheral registers example "
           "****************** \r\n\n");

    printf("Press 'p' for interrupts using peripheral registers\r\n\n");

    for (;;)
    {
        /* Check if 'p' key was pressed */
        if (cyhal_uart_getc(&cy_retarget_io_uart_obj, &uartReadValue, 1) == CY_RSLT_SUCCESS)
        {
            if (uartReadValue == 'p')
            {
                /* Set Interrupt for configured timer resource by software */
                Cy_TCPWM_SetInterrupt(TCPWM_PWM_HW, TCPWM_PWM_NUM, TCPWM_INTR_SOURCE);
            }
        }
    }
}

/* [] END OF FILE */
